trigger:
- master

variables:
  tag: v0.3.1

jobs:
- job: Build
  timeoutInMinutes: 0

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
      git clone https://github.com/trezor/blockbook.git -b $(tag)
    displayName: Cloning Blockblock repository.

  - script: |
      rm -f configs/coins/nuls.json
    workingDirectory: blockbook
    displayName: Removing unreliable coins.

  - script: |
      make all
    workingDirectory: blockbook
    displayName: Building

  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: blockbook/build/
